spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_events_db
    username: postgres
    password: franco
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql