spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_events_db?stringtype=unspecified
    username: franco
    password: franco
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
  sql:
    init:
      mode: always