spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_events_db
    username: franco
    password: franco
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true